// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCYL-4efgU3T1Ivqsl8nsuJc7w6sCCOGc',
    appId: '1:898772373587:android:784e501c99f6c6025536a6',
    messagingSenderId: '898772373587',
    projectId: 'minelab-fa1b1',
    storageBucket: 'minelab-fa1b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiOQbzqYuPZ4ev4cyvtSijCFq8rHbHgxA',
    appId: '1:898772373587:ios:6deeafb29d24f6f95536a6',
    messagingSenderId: '898772373587',
    projectId: 'minelab-fa1b1',
    storageBucket: 'minelab-fa1b1.firebasestorage.app',
    androidClientId:
        '898772373587-55ni4di8ql7auiscnsaqmo09e92q6rcm.apps.googleusercontent.com',
    iosClientId:
        '898772373587-rkub9494k9km0sdjoo8iuvs855v5okdm.apps.googleusercontent.com',
    iosBundleId: 'dev.vlab.mineLab',
  );
}
